version: 2

before:
  hooks:
    - go mod tidy
    # - go generate ./...

builds:
  - id: windows
    binary: windows
    env:
      - CGO_ENABLED=0
    goos:
      - windows
    ignore:
      - goos: windows
        goarch: arm64
  - id: other
    binary: other
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    ignore:
      - goos: linux
        goarch: 386

universal_binaries:
  replace: true

archives:
  - id: windows
    builds:
      - windows
    format: zip
    # this name template makes the OS and Arch compatible with the results of `uname`.
    name_template: >-
      {{  .ProjectName }}_{{ .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}{{ .Arm }}{{ end }}
  - id: other
    builds:
      - other
    format: tar.gz
    # this name template makes the OS and Arch compatible with the results of `uname`.
    name_template: >-
      {{  .ProjectName }}_{{ .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}{{ .Arm }}{{ end }}

release:
  prerelease: auto

brews:
  - # IDs of the archives to use.
    # Empty means all IDs.
    ids:
      - other
    commit_author:
      name: Ben Marshall
      email: benmarshall.dev@gmail.com
    commit_msg_template: "Brew formula update for {{ .ProjectName }} version {{ .Tag }}"
    directory: Formula
    url_template: "https://github.com/prattlOrg/prattl/releases/download/{{ .Tag }}/{{ .ArtifactName }}"
    homepage: "https://prattl.co/"
    description: "CLI tool for transcribing audio to text."
    license: "MIT"
    skip_upload: auto
    dependencies:
      - name: ffmpeg
    # Repository to push the generated files to.
    repository:
      owner: prattlOrg
      name: prattl
      branch: brew-releases/{{ .Version }}
      token: "{{ .Env.GITHUB_TOKEN }}"
      pull_request:
        enabled: true
        base:
          owner: prattlOrg
          name: prattl
          branch: main

chocolateys:
  - # IDs of the archives to use.
    # Empty means all IDs.
    # Attention: archives must not be in the 'binary' format.
    ids:
      - windows
    title: prattl
    authors:
      - Ben Marshall
      - Ezra Klitsie
    project_url: https://github.com/prattlOrg/prattl
    url_template: "https://github.com/prattlOrg/prattl/releases/download/{{ .Tag }}/{{ .ArtifactName }}"
    copyright: 2024 Prattl Org
    package_source_url: https://github.com/prattlOrg/prattl
    icon_url: "https://github.com/prattlOrg/prattl/blob/main/assets/logo.png"
    license_url: https://github.com/prattlOrg/prattl/blob/main/LICENSE
    require_license_acceptance: false
    project_source_url: https://github.com/prattlOrg/prattl
    docs_url: https://github.com/prattlOrg/prattl/blob/main/README.md
    bug_tracker_url: https://github.com/prattlOrg/prattl/issues
    tags: "transcription ai"
    summary: CLI tool for transcribing audio to text.
    description: |
      {{ .ProjectName }} installer package.
      CLI tool for transcribing audio to text.
    release_notes: "https://github.com/prattlOrg/prattl/releases/tag/{{ .Tag }}"
    dependencies:
      - id: ffmpeg
    # api_key: "{{ .Env.CHOCOLATEY_API_KEY }}"
    source_repo: "https://push.chocolatey.org/"
    skip_publish: false

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
